package com.wangxile.appparse;


import java.io.Serializable;

/**
 * generated by MyBatis Generator
 * corresponds to the database table saas_app_applet
 *
 * @mbg.generated Mon Dec 02 09:19:45 CST 2019
 */
public class SaasIosProvision implements Serializable {

    private static final long serialVersionUID = 6461585731094813076L;

    private String iosDescUrl;

    private String uuid;

    private String type;

    private String appId;

    private String platForm;

    private String createDate;

    private String expirationDate;

    private String teamName;

    private String teamIdentifier;

    private String apsEnvironment;

    private String nfcFormats;

    private String porvisionDevice;

    private Integer provisionAll;

    private Integer taskAllow;

    private String certificate;

    private String appidName;

    private String name;

    private Integer version;

    private String identifyPrefix;

    private Integer isXcode;

    private Integer wifiInfo;

    private String applicationGroup;

    private String associateDomain;

    private Integer credentialProvide;

    private String classkitEnvironment;

    private String dataProtection;

    private String keychainAccess;

    private Integer healthkit;

    private String healthkitAccess;

    private String appleTeamIdentifier;

    private Integer homekit;

    private Integer hotspotConfig;

    private String kvstoreIdentify;

    private String icloudServices;

    private String icloudIdentify;

    private String icloudDevIdentify;

    private String ubiquityIdentify;

    private Integer appAudio;

    private Integer netMultipath;

    private String netExtension;

    private Integer devSiri;

    private String vpnApi;

    private Integer wirelessConfig;

    private String passTypeIdenty;

    private String appPayment;

    private Integer hlsLowLatency;

    private String userFont;

    private String appleSign;

    public String getIosDescUrl() {
        return iosDescUrl;
    }

    public void setIosDescUrl(String iosDescUrl) {
        this.iosDescUrl = iosDescUrl;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getPlatForm() {
        return platForm;
    }

    public void setPlatForm(String platForm) {
        this.platForm = platForm;
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public String getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
    }

    public String getTeamName() {
        return teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    public String getTeamIdentifier() {
        return teamIdentifier;
    }

    public void setTeamIdentifier(String teamIdentifier) {
        this.teamIdentifier = teamIdentifier;
    }

    public String getApsEnvironment() {
        return apsEnvironment;
    }

    public void setApsEnvironment(String apsEnvironment) {
        this.apsEnvironment = apsEnvironment;
    }

    public String getNfcFormats() {
        return nfcFormats;
    }

    public void setNfcFormats(String nfcFormats) {
        this.nfcFormats = nfcFormats;
    }

    public String getPorvisionDevice() {
        return porvisionDevice;
    }

    public void setPorvisionDevice(String porvisionDevice) {
        this.porvisionDevice = porvisionDevice;
    }

    public Integer getProvisionAll() {
        return provisionAll;
    }

    public void setProvisionAll(Integer provisionAll) {
        this.provisionAll = provisionAll;
    }

    public Integer getTaskAllow() {
        return taskAllow;
    }

    public void setTaskAllow(Integer taskAllow) {
        this.taskAllow = taskAllow;
    }

    public String getCertificate() {
        return certificate;
    }

    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    public String getAppidName() {
        return appidName;
    }

    public void setAppidName(String appidName) {
        this.appidName = appidName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getIdentifyPrefix() {
        return identifyPrefix;
    }

    public void setIdentifyPrefix(String identifyPrefix) {
        this.identifyPrefix = identifyPrefix;
    }

    public Integer getIsXcode() {
        return isXcode;
    }

    public void setIsXcode(Integer isXcode) {
        this.isXcode = isXcode;
    }

    public Integer getWifiInfo() {
        return wifiInfo;
    }

    public void setWifiInfo(Integer wifiInfo) {
        this.wifiInfo = wifiInfo;
    }

    public String getApplicationGroup() {
        return applicationGroup;
    }

    public void setApplicationGroup(String applicationGroup) {
        this.applicationGroup = applicationGroup;
    }

    public String getAssociateDomain() {
        return associateDomain;
    }

    public void setAssociateDomain(String associateDomain) {
        this.associateDomain = associateDomain;
    }

    public Integer getCredentialProvide() {
        return credentialProvide;
    }

    public void setCredentialProvide(Integer credentialProvide) {
        this.credentialProvide = credentialProvide;
    }

    public String getClasskitEnvironment() {
        return classkitEnvironment;
    }

    public void setClasskitEnvironment(String classkitEnvironment) {
        this.classkitEnvironment = classkitEnvironment;
    }

    public String getDataProtection() {
        return dataProtection;
    }

    public void setDataProtection(String dataProtection) {
        this.dataProtection = dataProtection;
    }

    public String getKeychainAccess() {
        return keychainAccess;
    }

    public void setKeychainAccess(String keychainAccess) {
        this.keychainAccess = keychainAccess;
    }

    public Integer getHealthkit() {
        return healthkit;
    }

    public void setHealthkit(Integer healthkit) {
        this.healthkit = healthkit;
    }

    public String getHealthkitAccess() {
        return healthkitAccess;
    }

    public void setHealthkitAccess(String healthkitAccess) {
        this.healthkitAccess = healthkitAccess;
    }

    public String getAppleTeamIdentifier() {
        return appleTeamIdentifier;
    }

    public void setAppleTeamIdentifier(String appleTeamIdentifier) {
        this.appleTeamIdentifier = appleTeamIdentifier;
    }

    public Integer getHomekit() {
        return homekit;
    }

    public void setHomekit(Integer homekit) {
        this.homekit = homekit;
    }

    public Integer getHotspotConfig() {
        return hotspotConfig;
    }

    public void setHotspotConfig(Integer hotspotConfig) {
        this.hotspotConfig = hotspotConfig;
    }

    public String getKvstoreIdentify() {
        return kvstoreIdentify;
    }

    public void setKvstoreIdentify(String kvstoreIdentify) {
        this.kvstoreIdentify = kvstoreIdentify;
    }

    public String getIcloudServices() {
        return icloudServices;
    }

    public void setIcloudServices(String icloudServices) {
        this.icloudServices = icloudServices;
    }

    public String getIcloudIdentify() {
        return icloudIdentify;
    }

    public void setIcloudIdentify(String icloudIdentify) {
        this.icloudIdentify = icloudIdentify;
    }

    public String getIcloudDevIdentify() {
        return icloudDevIdentify;
    }

    public void setIcloudDevIdentify(String icloudDevIdentify) {
        this.icloudDevIdentify = icloudDevIdentify;
    }

    public String getUbiquityIdentify() {
        return ubiquityIdentify;
    }

    public void setUbiquityIdentify(String ubiquityIdentify) {
        this.ubiquityIdentify = ubiquityIdentify;
    }

    public Integer getAppAudio() {
        return appAudio;
    }

    public void setAppAudio(Integer appAudio) {
        this.appAudio = appAudio;
    }

    public Integer getNetMultipath() {
        return netMultipath;
    }

    public void setNetMultipath(Integer netMultipath) {
        this.netMultipath = netMultipath;
    }

    public String getNetExtension() {
        return netExtension;
    }

    public void setNetExtension(String netExtension) {
        this.netExtension = netExtension;
    }

    public Integer getDevSiri() {
        return devSiri;
    }

    public void setDevSiri(Integer devSiri) {
        this.devSiri = devSiri;
    }

    public String getVpnApi() {
        return vpnApi;
    }

    public void setVpnApi(String vpnApi) {
        this.vpnApi = vpnApi;
    }

    public Integer getWirelessConfig() {
        return wirelessConfig;
    }

    public void setWirelessConfig(Integer wirelessConfig) {
        this.wirelessConfig = wirelessConfig;
    }

    public String getPassTypeIdenty() {
        return passTypeIdenty;
    }

    public void setPassTypeIdenty(String passTypeIdenty) {
        this.passTypeIdenty = passTypeIdenty;
    }

    public String getAppPayment() {
        return appPayment;
    }

    public void setAppPayment(String appPayment) {
        this.appPayment = appPayment;
    }

    public Integer getHlsLowLatency() {
        return hlsLowLatency;
    }

    public void setHlsLowLatency(Integer hlsLowLatency) {
        this.hlsLowLatency = hlsLowLatency;
    }

    public String getUserFont() {
        return userFont;
    }

    public void setUserFont(String userFont) {
        this.userFont = userFont;
    }

    public String getAppleSign() {
        return appleSign;
    }

    public void setAppleSign(String appleSign) {
        this.appleSign = appleSign;
    }

    public String getPackType() {
        if ("enterprise".equals(this.getType()) || "ad-hoc".equals(this.getType())) {
            return "企业版";
        } else if ("development".equals(this.getType())) {
            return "内测版";
        } else {
            return "app-store版";
        }
    }
}